version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - skip-changelog
      - dependencies
    allow:
      - dependency-name: '@meilisearch/instant-meilisearch'
      - dependency-name: 'meilisearch'
      
